/* =============================================================
   CONSTITUENCIES - 140 single-member districts, first past the post.

   No list, no quota, no divisor: the list tier is a separate ballot
   (bible 4.1, parallel and NOT compensatory).

   held - one party, one seat, and the CURRENT roll rather than the last
   result. Every district total in the game derives from it; nothing is
   stored twice. test.js reconciles both ways.

   member - the name of the sitting member. Backbenchers, not characters:
   the roster in content/characters.js is still frozen (bible 2.7) and is
   still the only place a person with a portrait, a relationship and a
   grievance may be added. This field exists so that a seat on the map is
   somebody's seat rather than a party colour. Where a roster character
   sits for a seat the character wins, and the two agree here by hand.

   speaker - exactly one seat carries it. The member for that seat takes
   the Chair, sits apart from both benches in the seating plan, and wears
   the colour of whichever party holds the seat on the roll. The Chair is
   impartial in the House and partisan on the map, which is the truth of
   it: lose the seat at a by-election and the Chair changes hands.

   NAMING (bible 10.1). Register follows band, so a name carries its
   politics: civic and state vocabulary on the ring, trade in the middle,
   ordinary town names in the low band, water and green on the
   agricultural decks, plain and maritime outside.

   Double-barrelled names follow boundary-commission convention rather
   than taste. An em dash joins places amalgamated into one seat
   (Ellerby-Westmoor); an ampersand pairs two halves that kept their
   own identity (Chancery & Bell Yard); a plain hyphen appears only
   inside a single compound place name.

   Deprivation is NOT signalled in the low band's names. Real poor places
   are called Flint and Camden, not Slagworks; the poverty belongs in the
   tier, the closure figure and the grievance, all of which are already
   there. The exceptions are rationed and deliberate:
     Coldwater One and Coldwater Three, with no Two. Unexplained.
     Homestead A, Two, III, -04, Five, VI - six seats numbered in six
       systems because nobody ever agreed one.
     Tier Four, a rationing tier rather than a place name. Czarnecki sits
       for it, which is the tier his whole grievance is about.
   Space Elevator and The Beanstalk are one structure named officially
   and colloquially, adjacent on purpose. The Warrens carries an
   `official` name nobody uses, from the suppression.

   "Proper" (Anselm Proper, Meridian Proper) is the built-up core as
   against the periphery - the orbital equivalent of a Metro riding.
   ============================================================= */

const CONSTITUENCIES = [

  { id:"anselm_proper", name:"Anselm Proper", station:"anselm", band:"ring",
    magnitude:1, electorate:27392,
    member:"Kofi Ashworth",
    held:{cl:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"charter_green", name:"Charter Green", station:"anselm", band:"ring",
    magnitude:1, electorate:33783,
    member:"Otto Rakoto",
    held:{cl:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"concord_bellfield", name:"Concord—Bellfield", station:"anselm", band:"ring",
    magnitude:1, electorate:30230,
    member:"Perpetua Ndiaye",
    held:{rv:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"first_spin", name:"First Spin", station:"anselm", band:"ring",
    magnitude:1, electorate:34743,
    member:"Adriana Flash",
    held:{cu:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_long_gallery", name:"The Long Gallery", station:"anselm", band:"ring",
    magnitude:1, electorate:32034,
    member:"Lucian Peverell",
    held:{sc:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"assembly_walk", name:"Assembly Walk", station:"anselm", band:"ring",
    magnitude:1, electorate:35276,
    member:"Isolde Abiodun",
    held:{cl:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"allocation_square", name:"Allocation Square", station:"anselm", band:"ring",
    magnitude:1, electorate:29768,
    member:"Tomas Kirilenko",
    held:{cl:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_exchange", name:"The Exchange", station:"anselm", band:"ring",
    magnitude:1, electorate:33260,
    member:"Gustav Leclair",
    held:{cl:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"registry_walk", name:"Registry Walk", station:"anselm", band:"ring",
    magnitude:1, electorate:33363,
    member:"Rowan Aldiss",
    held:{cu:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"chancery_and_bell_yard", name:"Chancery & Bell Yard", station:"anselm", band:"ring",
    magnitude:1, electorate:35004,
    member:"Solveig Ilyin",
    speaker:true,
    held:{cu:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"quorum", name:"Quorum", station:"anselm", band:"ring",
    magnitude:1, electorate:29789,
    member:"Lucian Okafor",
    held:{rv:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_cisterns", name:"The Cisterns", station:"anselm", band:"ring",
    magnitude:1, electorate:27591,
    member:"Viggo Vane",
    held:{rv:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"cress_walk_wellhead", name:"Cress Walk—Wellhead", station:"anselm", band:"ring",
    magnitude:1, electorate:28200,
    member:"Hakim Amankwah",
    held:{rv:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_beds", name:"The Beds", station:"anselm", band:"ring",
    magnitude:1, electorate:28779,
    member:"Petra Prentice",
    held:{cu:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"orchard_deck_and_vine_end", name:"Orchard Deck & Vine End", station:"anselm", band:"ring",
    magnitude:1, electorate:27578,
    member:"Talia Sturridge",
    held:{sc:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"hollowmere", name:"Hollowmere", station:"anselm", band:"ring",
    magnitude:1, electorate:29863,
    member:"Tamsin Marchetti",
    held:{cu:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"ropewalk", name:"Ropewalk", station:"anselm", band:"ring",
    magnitude:1, electorate:34996,
    member:"Anil Devi",
    held:{cu:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"kiln_end_cordage", name:"Kiln End—Cordage", station:"anselm", band:"ring",
    magnitude:1, electorate:33563,
    member:"Prue Kabelo",
    held:{cu:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"drybank", name:"Drybank", station:"anselm", band:"ring",
    magnitude:1, electorate:34816,
    member:"Rafiq Aliyev",
    held:{fh:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"coopers_walk", name:"Coopers Walk", station:"anselm", band:"ring",
    magnitude:1, electorate:31131,
    member:"Viggo Okonkwo",
    held:{sc:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"saltings_and_ferrylane", name:"Saltings & Ferrylane", station:"anselm", band:"ring",
    magnitude:1, electorate:31464,
    member:"Mireille Crowther",
    held:{cu:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"spinward_reach", name:"Spinward Reach", station:"anselm", band:"ring",
    magnitude:1, electorate:32640,
    member:"Noor Cottrell",
    held:{cu:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"windward_leeside", name:"Windward—Leeside", station:"anselm", band:"ring",
    magnitude:1, electorate:30862,
    member:"Constance Petrov",
    held:{cl:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"longwall", name:"Longwall", station:"anselm", band:"ring",
    magnitude:1, electorate:28902,
    member:"Ilse Sturridge",
    held:{sc:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"marlowe_green", name:"Marlowe Green", station:"anselm", band:"ring",
    magnitude:1, electorate:27659,
    member:"Viggo Rasmussen",
    held:{cl:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"space_elevator", name:"Space Elevator", station:"anselm", band:"ring",
    magnitude:1, electorate:28032,
    member:"Hollis Kaur",
    held:{cl:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_beanstalk", name:"The Beanstalk", station:"anselm", band:"ring",
    magnitude:1, electorate:28705,
    member:"Piotr Ilyin",
    held:{cu:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"anchor_head_cable_row", name:"Anchor Head—Cable Row", station:"anselm", band:"ring",
    magnitude:1, electorate:28057,
    member:"Hollis Vane",
    held:{cu:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_counterweight", name:"The Counterweight", station:"anselm", band:"ring",
    magnitude:1, electorate:29045,
    member:"Nadia Okafor",
    held:{hul:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"fetterlane", name:"Fetterlane", station:"anselm", band:"ring",
    magnitude:1, electorate:27485,
    member:"Elowen Amankwah",
    held:{cu:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"deep_deck", name:"Deep Deck", station:"anselm", band:"ring",
    magnitude:1, electorate:35028,
    member:"Mireille Blaise",
    held:{cu:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"underwall_and_lowwater", name:"Underwall & Lowwater", station:"anselm", band:"ring",
    magnitude:1, electorate:28437,
    member:"Runa Whitlock",
    held:{cu:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"the_sinks", name:"The Sinks", station:"anselm", band:"ring",
    magnitude:1, electorate:35235,
    member:"Constance Ilyin",
    held:{sc:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"blackfriars", name:"Blackfriars", station:"anselm", band:"ring",
    magnitude:1, electorate:29714,
    member:"Prue Leclair",
    held:{cl:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"old_foundation", name:"Old Foundation", station:"anselm", band:"ring",
    magnitude:1, electorate:31700,
    member:"Elsa Zubiri",
    held:{cl:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"charter_house_sessions", name:"Charter House—Sessions", station:"anselm", band:"ring",
    magnitude:1, electorate:31179,
    member:"Marta Ubeda",
    held:{fh:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"ambrose_fields", name:"Ambrose Fields", station:"anselm", band:"ring",
    magnitude:1, electorate:33800,
    member:"Piotr Idowu",
    held:{cu:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"belvedere_centre", name:"Belvedere Centre", station:"belvedere", band:"ring",
    magnitude:1, electorate:29170,
    member:"Marta Rasmussen",
    held:{fh:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"kingsmere", name:"Kingsmere", station:"belvedere", band:"ring",
    magnitude:1, electorate:28218,
    member:"Lior Onyema",
    held:{psa:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"fallbrook_aldergate", name:"Fallbrook—Aldergate", station:"belvedere", band:"ring",
    magnitude:1, electorate:28499,
    member:"Greta Fairweather",
    held:{fh:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"meridian_proper", name:"Meridian Proper", station:"meridian", band:"ring",
    magnitude:1, electorate:26752,
    member:"Ottoline Winterbourne",
    held:{cu:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"meridian_drum", name:"Meridian Drum", station:"meridian", band:"ring",
    magnitude:1, electorate:24681,
    member:"Zora Lindqvist",
    held:{cu:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"meridian_loop", name:"Meridian Loop", station:"meridian", band:"ring",
    magnitude:1, electorate:27614,
    member:"Halima Okafor",
    held:{cl:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"east_gallery_and_sailmakers", name:"East Gallery & Sailmakers", station:"meridian", band:"ring",
    magnitude:1, electorate:25907,
    member:"Kestrel Vane",
    held:{sc:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"meridian_yard", name:"Meridian Yard", station:"meridian", band:"ring",
    magnitude:1, electorate:21673,
    member:"Mabel Zubiri",
    held:{cu:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"west_gallery", name:"West Gallery", station:"meridian", band:"ring",
    magnitude:1, electorate:23884,
    member:"Constance Ashby",
    held:{cu:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"thrale_whitcomb", name:"Thrale—Whitcomb", station:"meridian", band:"ring",
    magnitude:1, electorate:27516,
    member:"Magnus Okonkwo",
    held:{cl:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"halyard_row", name:"Halyard Row", station:"meridian", band:"ring",
    magnitude:1, electorate:26921,
    member:"Neve Okafor",
    held:{sc:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"cable_end", name:"Cable End", station:"meridian", band:"ring",
    magnitude:1, electorate:28038,
    member:"Caspar Crowther",
    held:{cl:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"anchor_walk", name:"Anchor Walk", station:"meridian", band:"ring",
    magnitude:1, electorate:26441,
    member:"Rowan Castellan",
    held:{cl:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"the_winding", name:"The Winding", station:"meridian", band:"ring",
    magnitude:1, electorate:23579,
    member:"Perpetua Zubiri",
    held:{cu:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"counterweight_row", name:"Counterweight Row", station:"meridian", band:"ring",
    magnitude:1, electorate:24336,
    member:"Amias Kingsley",
    held:{hul:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"underdecks", name:"Underdecks", station:"meridian", band:"ring",
    magnitude:1, electorate:22192,
    member:"Thandi Thorne",
    held:{cu:1},
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"trentham_lowbay", name:"Trentham—Lowbay", station:"meridian", band:"ring",
    magnitude:1, electorate:28502,
    member:"Ilse Adeyemi",
    held:{cu:1},
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"the_warrens", name:"The Warrens", station:"meridian", band:"ring",
    magnitude:1, electorate:23094,
    member:"Tomas Halstead",
    held:{psa:1},
    official:"Loyalty Row",
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"ostler_green", name:"Ostler Green", station:"meridian", band:"ring",
    magnitude:1, electorate:22833,
    member:"Odell Ashworth",
    held:{sc:1},
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"] },

  { id:"rookworks_centre", name:"Rookworks Centre", station:"corvus", band:"ring",
    magnitude:1, electorate:26685,
    member:"Lars Abiodun",
    held:{cl:1},
    parent:"corvus_ring_inner",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"rookworks_east", name:"Rookworks East", station:"corvus", band:"ring",
    magnitude:1, electorate:30836,
    member:"Silas Balogun",
    held:{cl:1},
    parent:"corvus_ring_inner",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"rookery_and_nestgate", name:"Rookery & Nestgate", station:"corvus", band:"ring",
    magnitude:1, electorate:29266,
    member:"Faisal Sandoval",
    held:{cu:1},
    parent:"corvus_ring_inner",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"crowfield", name:"Crowfield", station:"corvus", band:"ring",
    magnitude:1, electorate:26883,
    member:"Amara Ossory",
    held:{cu:1},
    parent:"corvus_ring_outer",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"bellmouth_dunnock", name:"Bellmouth—Dunnock", station:"corvus", band:"ring",
    magnitude:1, electorate:32507,
    member:"Silas Chikelu",
    held:{cu:1},
    parent:"corvus_ring_outer",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"vesper_row", name:"Vesper Row", station:"corvus", band:"ring",
    magnitude:1, electorate:27373,
    member:"Marisol Mensah",
    held:{sc:1},
    parent:"corvus_ring_outer",
    material_interest:["tether_traffic", "volume_rationing"] },

  { id:"bondsville_centre", name:"Bondsville Centre", station:"sable", band:"ring",
    magnitude:1, electorate:33231,
    member:"Agnes Novak",
    held:{sc:1},
    parent:"sable_drum_rim",
    material_interest:["tether_traffic", "consumables_subsidy"] },

  { id:"the_rim", name:"The Rim", station:"sable", band:"ring",
    magnitude:1, electorate:29491,
    member:"Annika Torrance",
    held:{sc:1},
    parent:"sable_drum_rim",
    material_interest:["tether_traffic", "consumables_subsidy"] },

  { id:"drumhead", name:"Drumhead", station:"sable", band:"ring",
    magnitude:1, electorate:28583,
    member:"Constance Ekwueme",
    held:{cu:1},
    parent:"sable_drum_rim",
    material_interest:["tether_traffic", "consumables_subsidy"] },

  { id:"leaseside_rentfield", name:"Leaseside—Rentfield", station:"sable", band:"ring",
    magnitude:1, electorate:33162,
    member:"Rafiq Merrick",
    held:{fh:1},
    parent:"sable_leaseside",
    material_interest:["tether_traffic", "consumables_subsidy"] },

  { id:"tollgate", name:"Tollgate", station:"sable", band:"ring",
    magnitude:1, electorate:30629,
    member:"Rosalind Kirilenko",
    held:{fh:1},
    parent:"sable_leaseside",
    material_interest:["tether_traffic", "consumables_subsidy"] },

  { id:"marbury", name:"Marbury", station:"sable", band:"ring",
    magnitude:1, electorate:31485,
    member:"Signe Marren",
    held:{fh:1},
    parent:"sable_leaseside",
    material_interest:["tether_traffic", "consumables_subsidy"] },

  { id:"halvard_centre", name:"Halvard Centre", station:"halvard", band:"ring",
    magnitude:1, electorate:31314,
    member:"Signe Crowther",
    held:{cl:1},
    parent:"halvard_terrace",
    material_interest:["volume_rationing", "tether_traffic"] },

  { id:"the_crescent", name:"The Crescent", station:"halvard", band:"ring",
    magnitude:1, electorate:31559,
    member:"Ezra Aldiss",
    held:{cl:1},
    parent:"halvard_terrace",
    material_interest:["volume_rationing", "tether_traffic"] },

  { id:"parade_row_and_ivens", name:"Parade Row & Ivens", station:"halvard", band:"ring",
    magnitude:1, electorate:27752,
    member:"Idris Novak",
    held:{fh:1},
    parent:"halvard_terrace",
    material_interest:["volume_rationing", "tether_traffic"] },

  { id:"the_bourse", name:"The Bourse", station:"bourse", band:"ring",
    magnitude:1, electorate:8717,
    member:"Prue Strand",
    held:{cl:1},
    parent:"the_bourse",
    material_interest:["risk_pricing", "substrate_supply"] },

  { id:"exchange_alley_threadmarket", name:"Exchange Alley—Threadmarket", station:"bourse", band:"ring",
    magnitude:1, electorate:10830,
    member:"Tomas Winterbourne",
    held:{cl:1},
    parent:"the_bourse",
    material_interest:["risk_pricing", "substrate_supply"] },

  { id:"brant_north", name:"Brant North", station:"hollows", band:"far",
    magnitude:1, electorate:38090,
    member:"Otto Mainwaring",
    held:{rv:1},
    parent:"hollows_north",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"brant_south", name:"Brant South", station:"hollows", band:"far",
    magnitude:1, electorate:34083,
    member:"Otto Lowry",
    held:{sc:1},
    parent:"hollows_north",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"ellery", name:"Ellery", station:"hollows", band:"far",
    magnitude:1, electorate:40880,
    member:"Freya Copeland",
    held:{rv:1},
    parent:"hollows_south",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"ellery_cross_thin_air", name:"Ellery Cross—Thin Air", station:"hollows", band:"far",
    magnitude:1, electorate:41140,
    member:"Amias Castellan",
    held:{sc:1},
    parent:"hollows_south",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"kincaid", name:"Kincaid", station:"hollows", band:"far",
    magnitude:1, electorate:34645,
    member:"Faisal Lindholm",
    held:{rv:1},
    parent:"hollows_cross",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"merrow", name:"Merrow", station:"hollows", band:"far",
    magnitude:1, electorate:35059,
    member:"Ingrid Wexford",
    held:{rv:1},
    parent:"hollows_cross",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"farstead_centre", name:"Farstead Centre", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:38208,
    member:"Boyd Mwangi",
    held:{hul:1},
    parent:"tsiolkovsky_north",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"the_rackworks", name:"The Rackworks", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:35582,
    member:"Gerard Stannard",
    held:{sc:1},
    parent:"tsiolkovsky_north",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"substrate_quarter", name:"Substrate Quarter", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:33408,
    member:"Beatrix Pemberton",
    held:{psa:1},
    parent:"tsiolkovsky_substrate_quarter",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"cold_storage_and_dray_end", name:"Cold Storage & Dray End", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:40290,
    member:"Malachy Vasquez",
    held:{psa:1},
    parent:"tsiolkovsky_substrate_quarter",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"coldwater_one", name:"Coldwater One", station:"coldharbour", band:"far",
    magnitude:1, electorate:36965,
    member:"Cleo Larsen",
    held:{psa:1},
    parent:"coldharbour_racks",
    material_interest:["substrate_supply", "thermal_quota", "shed_order_priority"] },

  { id:"coldwater_three", name:"Coldwater Three", station:"coldharbour", band:"far",
    magnitude:1, electorate:32929,
    member:"Tamsin Redfern",
    held:{hul:1},
    parent:"coldharbour_shed",
    material_interest:["substrate_supply", "thermal_quota", "shed_order_priority"] },

  { id:"amphitheatre", name:"Amphitheatre", station:"erasmus", band:"far",
    magnitude:1, electorate:27941,
    member:"Solveig Whitlock",
    held:{psa:1},
    parent:"erasmus_deck",
    material_interest:["substrate_supply", "licensure_scope"] },

  { id:"scholarsgate_quill", name:"Scholarsgate—Quill", station:"erasmus", band:"far",
    magnitude:1, electorate:22406,
    member:"Idris Nakamura",
    held:{sc:1},
    parent:"erasmus_deck",
    material_interest:["substrate_supply", "licensure_scope"] },

  { id:"the_array", name:"The Array", station:"nasmyth", band:"far",
    magnitude:1, electorate:10492,
    member:"Freya Ferrand",
    held:{hul:1},
    parent:"nasmyth_array",
    material_interest:["thermal_quota", "yard_contracts"] },

  { id:"hammerside_and_deverell", name:"Hammerside & Deverell", station:"nasmyth", band:"far",
    magnitude:1, electorate:12016,
    member:"Sten Ganev",
    held:{sc:1},
    parent:"nasmyth_array",
    material_interest:["thermal_quota", "yard_contracts"] },

  { id:"luminaire", name:"Luminaire", station:"vantage", band:"middle",
    magnitude:1, electorate:29583,
    member:"Runa Danjuma",
    held:{cu:1},
    parent:"vantage_high",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"the_overlook", name:"The Overlook", station:"vantage", band:"middle",
    magnitude:1, electorate:34225,
    member:"Kestrel Aldiss",
    held:{hul:1},
    parent:"vantage_high",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"radiator_row_coldside", name:"Radiator Row—Coldside", station:"vantage", band:"middle",
    magnitude:1, electorate:32250,
    member:"Sunniva Adebayo",
    held:{cu:1},
    parent:"vantage_radiator_row",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"selwyn_park", name:"Selwyn Park", station:"vantage", band:"middle",
    magnitude:1, electorate:30106,
    member:"Casimir Marchetti",
    held:{sc:1},
    parent:"vantage_radiator_row",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"the_yards", name:"The Yards", station:"perigee", band:"middle",
    magnitude:1, electorate:24993,
    member:"Gustav Stannard",
    held:{hul:1},
    parent:"perigee_yards",
    material_interest:["tether_traffic", "yard_contracts"] },

  { id:"dry_dock_and_marden", name:"Dry Dock & Marden", station:"perigee", band:"middle",
    magnitude:1, electorate:30985,
    member:"Ruslan Fenwick",
    held:{hul:1},
    parent:"perigee_yards",
    material_interest:["tether_traffic", "yard_contracts"] },

  { id:"slipway", name:"Slipway", station:"perigee", band:"middle",
    magnitude:1, electorate:29316,
    member:"Suravaram Vidyasagar",
    held:{cu:1},
    parent:"perigee_yards",
    material_interest:["tether_traffic", "yard_contracts"] },

  { id:"the_loop", name:"The Loop", station:"calloway", band:"middle",
    magnitude:1, electorate:31643,
    member:"Idris Kaur",
    held:{cu:1},
    parent:"calloway_loop",
    material_interest:["shed_order_priority", "consumables_subsidy"] },

  { id:"calloway_green_tewkes", name:"Calloway Green—Tewkes", station:"calloway", band:"middle",
    magnitude:1, electorate:38251,
    member:"Runa Salih",
    held:{sc:1},
    parent:"calloway_loop",
    material_interest:["shed_order_priority", "consumables_subsidy"] },

  { id:"layover_centre", name:"Layover Centre", station:"grimaldi", band:"middle",
    magnitude:1, electorate:28441,
    member:"Juno Camberwell",
    held:{cl:1},
    parent:"grimaldi_station",
    material_interest:["transit_windows", "tether_traffic"] },

  { id:"transit_row", name:"Transit Row", station:"grimaldi", band:"middle",
    magnitude:1, electorate:34345,
    member:"Talia Balogun",
    held:{sc:1},
    parent:"grimaldi_station",
    material_interest:["transit_windows", "tether_traffic"] },

  { id:"passerine", name:"Passerine", station:"wickstead", band:"middle",
    magnitude:1, electorate:41462,
    member:"Delphine Blaise",
    held:{sc:1},
    parent:"wickstead",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"the_approach", name:"The Approach", station:"oberth", band:"middle",
    magnitude:1, electorate:33170,
    member:"Oona Sardar",
    held:{rv:1},
    parent:"oberth_approach",
    material_interest:["embodiment_access", "bone_density_standards"] },

  { id:"the_tannery", name:"The Tannery", station:"tannery", band:"middle",
    magnitude:1, electorate:13872,
    member:"Hakim Rasmussen",
    held:{cu:1},
    parent:"the_tannery",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"skinners_row_and_barkfield", name:"Skinners Row & Barkfield", station:"tannery", band:"middle",
    magnitude:1, electorate:13967,
    member:"Leontine Abiodun",
    held:{rv:1},
    parent:"the_tannery",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"homestead_a", name:"Homestead A", station:"ashfield", band:"low",
    magnitude:1, electorate:32992,
    member:"Rosalind Grimsby",
    held:{ind:1},
    parent:"ashfield_a_c",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_two", name:"Homestead Two", station:"ashfield", band:"low",
    magnitude:1, electorate:34149,
    member:"Nikolai Bassey",
    held:{cu:1},
    parent:"ashfield_a_c",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_iii", name:"Homestead III", station:"ashfield", band:"low",
    magnitude:1, electorate:35165,
    member:"Osman Marren",
    held:{cu:1},
    parent:"ashfield_a_c",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_04", name:"Homestead-04", station:"ashfield", band:"low",
    magnitude:1, electorate:30474,
    member:"Dmitri Ubeda",
    held:{cu:1},
    parent:"ashfield_d_f",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_five", name:"Homestead Five", station:"ashfield", band:"low",
    magnitude:1, electorate:33575,
    member:"Faisal Winterbourne",
    held:{cu:1},
    parent:"ashfield_d_f",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_vi", name:"Homestead VI", station:"ashfield", band:"low",
    magnitude:1, electorate:32049,
    member:"Tamsin Weatherly",
    held:{sc:1},
    parent:"ashfield_d_f",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"marchmont", name:"Marchmont", station:"ashfield", band:"low",
    magnitude:1, electorate:38969,
    member:"Elsa Sandoval",
    held:{cu:1},
    parent:"ashfield_g_j",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"ellerby_westmoor", name:"Ellerby—Westmoor", station:"ashfield", band:"low",
    magnitude:1, electorate:30141,
    member:"Nkechi Varga",
    held:{cu:1},
    parent:"ashfield_g_j",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"norbury", name:"Norbury", station:"ashfield", band:"low",
    magnitude:1, electorate:38475,
    member:"Gustav Aldiss",
    held:{cu:1},
    parent:"ashfield_g_j",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"kiln_green", name:"Kiln Green", station:"ashfield", band:"low",
    magnitude:1, electorate:35614,
    member:"Zora Rasmussen",
    held:{cu:1},
    parent:"ashfield_slagside",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"bellrow_and_lowgate", name:"Bellrow & Lowgate", station:"ashfield", band:"low",
    magnitude:1, electorate:38635,
    member:"Kofi Ubeda",
    held:{cu:1},
    parent:"ashfield_slagside",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"tier_four", name:"Tier Four", station:"ashfield", band:"low",
    magnitude:1, electorate:30208,
    member:"Dan Czarnecki",
    held:{cu:1},
    parent:"ashfield_slagside",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"the_cans", name:"The Cans", station:"ashfield", band:"low",
    magnitude:1, electorate:38981,
    member:"Verity Ozols",
    held:{cu:1},
    parent:"ashfield_tier_four",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"hetherleigh", name:"Hetherleigh", station:"ashfield", band:"low",
    magnitude:1, electorate:38049,
    member:"Lars Sardar",
    held:{cu:1},
    parent:"ashfield_tier_four",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"padstow_deck", name:"Padstow Deck", station:"ashfield", band:"low",
    magnitude:1, electorate:33767,
    member:"Zainab Merrick",
    held:{sc:1},
    parent:"ashfield_tier_four",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"high_southwark", name:"High Southwark", station:"kepler", band:"low",
    magnitude:1, electorate:33529,
    member:"Rowan Blaise",
    held:{des:1},
    parent:"kepler_anchorage",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"high_lagos", name:"High Lagos", station:"kepler", band:"low",
    magnitude:1, electorate:35660,
    member:"Otto Pemberton",
    held:{sc:1},
    parent:"kepler_anchorage",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"anchor_row_concession", name:"Anchor Row—Concession", station:"kepler", band:"low",
    magnitude:1, electorate:33698,
    member:"Freya Aldiss",
    held:{cl:1},
    parent:"kepler_concession",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"brightwell", name:"Brightwell", station:"kepler", band:"low",
    magnitude:1, electorate:33939,
    member:"Marta Peverell",
    held:{des:1},
    parent:"kepler_concession",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"hardie_centre", name:"Hardie Centre", station:"slagworks", band:"low",
    magnitude:1, electorate:33601,
    member:"Leontine Ossory",
    held:{cu:1},
    parent:"slagworks",
    material_interest:["consumables_subsidy", "yard_contracts"] },

  { id:"clearmont_and_sowerby", name:"Clearmont & Sowerby", station:"slagworks", band:"low",
    magnitude:1, electorate:37478,
    member:"Dmitri Kirilenko",
    held:{ind:1},
    parent:"slagworks",
    material_interest:["consumables_subsidy", "yard_contracts"] },

  { id:"sunman_centre", name:"Sunman Centre", station:"bellows", band:"low",
    magnitude:1, electorate:25934,
    member:"Idris Kabelo",
    held:{cu:1},
    parent:"bellows",
    material_interest:["thermal_quota", "consumables_subsidy"] },

  { id:"lindenhall_peck", name:"Lindenhall—Peck", station:"bellows", band:"low",
    magnitude:1, electorate:33890,
    member:"Leontine Kaur",
    held:{hul:1},
    parent:"bellows",
    material_interest:["thermal_quota", "consumables_subsidy"] },

  { id:"lantern", name:"Lantern", station:"cinder", band:"low",
    magnitude:1, electorate:46203,
    member:"Osman Brannigan",
    held:{cu:1},
    parent:"cinder",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"pavilion", name:"Pavilion", station:"tallow", band:"low",
    magnitude:1, electorate:38501,
    member:"Nkechi Lindholm",
    held:{rv:1},
    parent:"tallow",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"stanbridge", name:"Stanbridge", station:"quarry", band:"low",
    magnitude:1, electorate:34355,
    member:"Marek Vasquez",
    held:{ind:1},
    parent:"quarry_reach",
    material_interest:["yard_contracts", "transit_windows"] },

  { id:"verge_north", name:"Verge North", station:"drift", band:"low",
    magnitude:1, electorate:21703,
    member:"Nikolai Onyema",
    held:{cu:1},
    parent:"drift_cans_north",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"verge_south_and_halloway", name:"Verge South & Halloway", station:"drift", band:"low",
    magnitude:1, electorate:25090,
    member:"Kwame Sturridge",
    held:{cu:1},
    parent:"drift_cans_south",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"colonnade", name:"Colonnade", station:"sinter", band:"low",
    magnitude:1, electorate:13128,
    member:"Brennan Kettering",
    held:{ind:1},
    parent:"sinter",
    material_interest:["yard_contracts", "consumables_subsidy"] },

  { id:"wrenfield_aubrey", name:"Wrenfield—Aubrey", station:"sinter", band:"low",
    magnitude:1, electorate:12934,
    member:"Nadia Castellan",
    held:{ind:1},
    parent:"sinter",
    material_interest:["yard_contracts", "consumables_subsidy"] },

  { id:"john_henry", name:"John Henry", station:"dredge", band:"low",
    magnitude:1, electorate:20139,
    member:"Beatrix Merrick",
    held:{ind:1},
    parent:"dredge",
    material_interest:["transit_windows", "yard_contracts"] },

  { id:"groundside", name:"Groundside", station:"selene", band:"external",
    magnitude:1, electorate:35539,
    member:"Elowen Halstead",
    held:{des:1},
    parent:"selene_stations",
    material_interest:["transit_windows"] },

  { id:"the_bloomery", name:"The Bloomery", station:"bloomery", band:"external",
    magnitude:1, electorate:14216,
    member:"Piotr Trelawny",
    held:{sc:1},
    parent:"the_bloomery",
    material_interest:["transit_windows", "yard_contracts"] },

  { id:"fast_anchor", name:"Fast Anchor", station:"l4", band:"external",
    magnitude:1, electorate:14808,
    member:"Rosalind Hollister",
    held:{sc:1},
    parent:"l4_yards",
    material_interest:["transit_windows", "substrate_supply"] },

  { id:"far_mooring", name:"Far Mooring", station:"achenar", band:"external",
    magnitude:1, electorate:7700,
    member:"Gustav Brightwater",
    held:{sc:1},
    parent:"achenar_point",
    material_interest:["transit_windows", "substrate_supply"] },

  { id:"sanctuary", name:"Sanctuary", station:"l5", band:"external",
    magnitude:1, electorate:6516,
    member:"Solveig Halstead",
    held:{rv:1},
    parent:"l5_refuge",
    material_interest:["transit_windows"] },
];
