/* =============================================================
   CONSTITUENCIES - 140 single-member districts, first past the post.

   No list, no quota, no divisor: the list tier is a separate ballot
   (bible 4.1, parallel and NOT compensatory).

   held - one party, one seat, and the CURRENT roll rather than the last
   result. Every district total in the game derives from it; nothing is
   stored twice. test.js reconciles both ways.

   member - the name of the sitting member. Backbenchers, not characters:
   the roster in content/characters.js is still frozen (bible 2.7) and is
   still the only place a person with a portrait, a relationship and a
   grievance may be added. This field exists so that a seat on the map is
   somebody's seat rather than a party colour. Where a roster character
   sits for a seat the character wins, and the two agree here by hand.

   speaker - exactly one seat carries it. The member for that seat takes
   the Chair, sits apart from both benches in the seating plan, and wears
   the colour of whichever party holds the seat on the roll. The Chair is
   impartial in the House and partisan on the map, which is the truth of
   it: lose the seat at a by-election and the Chair changes hands.

   NAMING (bible 10.1). Register follows band, so a name carries its
   politics: civic and state vocabulary on the ring, trade in the middle,
   ordinary town names in the low band, water and green on the
   agricultural decks, plain and maritime outside.

   Double-barrelled names follow boundary-commission convention rather
   than taste. An em dash joins places amalgamated into one seat
   (Ellerby-Westmoor); an ampersand pairs two halves that kept their
   own identity (Chancery & Bell Yard); a plain hyphen appears only
   inside a single compound place name.

   Deprivation is NOT signalled in the low band's names. Real poor places
   are called Flint and Camden, not Slagworks; the poverty belongs in the
   tier, the closure figure and the grievance, all of which are already
   there. The exceptions are rationed and deliberate:
     Coldwater One and Coldwater Three, with no Two. Unexplained.
     Homestead A, Two, III, -04, Five, VI - six seats numbered in six
       systems because nobody ever agreed one.
     Tier Four, a rationing tier rather than a place name. Czarnecki sits
       for it, which is the tier his whole grievance is about.
   Space Elevator and The Beanstalk are one structure named officially
   and colloquially, adjacent on purpose. The Warrens carries an
   `official` name nobody uses, from the suppression.

   "Proper" (Anselm Proper, Meridian Proper) is the built-up core as
   against the periphery - the orbital equivalent of a Metro riding.
   ============================================================= */

const CONSTITUENCIES = [

  { id:"anselm_proper", name:"Anselm Proper", station:"anselm", band:"ring",
    magnitude:1, electorate:27392,
    member:"Kofi Ashworth",
    held:{cl:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The built-up core of Anselm Ring and the largest electorate in the station. Its economy is the tether schedule and the volume market, the two interests the seat has recorded at every election, and it returns one of the ring's safest Liberal members. Turnout is the highest in the band, which flatters the incumbent and conceals how little local organisation the party keeps.",
    tendency:"Market-liberal and managerial, held since the founding on a roll of 27,392 and an apportionment ratio of 1.08, which is over-represented against a Commonwealth mean of 1.00. It has not been seriously contested in a decade, and the vote moves on two questions only: the tether schedule and the volume rent." },

  { id:"charter_green", name:"Charter Green", station:"anselm", band:"ring",
    magnitude:1, electorate:33783,
    member:"Otto Rakoto",
    held:{cl:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A green belt on the station's inner face, laid out to the Charter's original plan and never built over. The electorate is professional and larger than the station average; the recorded interests are tether traffic and volume rationing, neither of which has ever decided the seat.",
    tendency:"Liberal with a strong institutional streak, on a roll of 33,783 and a ratio of 0.88, which is under-represented against the mean. The vote here is about the founding document rather than the party, and the last serious challenge, a Democratic Centre campaign on the personhood line, did not come close to carrying the seat." },

  { id:"concord_bellfield", name:"Concord—Bellfield", station:"anselm", band:"ring",
    magnitude:1, electorate:30230,
    member:"Perpetua Ndiaye",
    held:{rv:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Two districts joined at a boundary review: Concord, the old administrative quarter, and Bellfield, the terraces behind it. The electorate is mixed and the seat is the Democratic Centre's safest in the ring band. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left-leaning but restrictionist, on a roll of 30,230 and a ratio of 0.98. The majority is personal to the member rather than structural; on the party's own numbers the seat would be competitive without her. Continuity-of-soul politics is stronger in the terraces and weaker in the old quarter." },

  { id:"first_spin", name:"First Spin", station:"anselm", band:"ring",
    magnitude:1, electorate:34743,
    member:"Adriana Flash",
    held:{cu:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The first spin of the ring, where the pressure fitters live, and the Prime Minister's own seat. The electorate is large and unionised; the recorded interests are tether traffic and volume rationing.",
    tendency:"Left and embodied-labour, on a roll of 34,743 and a ratio of 0.85, which is under-represented against the mean. The majority is large and personal to the Prime Minister, and the seat has not fallen since the founding. A swing here is read nationally before the count is finished." },

  { id:"the_long_gallery", name:"The Long Gallery", station:"anselm", band:"ring",
    magnitude:1, electorate:32034,
    member:"Lucian Peverell",
    held:{sc:1},
    parent:"anselm_ring_north",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A kilometre-long arcade that became a district. Market stalls run it by day and the station's loudest politics by night. The recorded interests are tether traffic and volume rationing.",
    tendency:"Confederalist, and the one seat in Anselm where home rule sells, on a roll of 32,034 and a ratio of 0.93. The vote does not travel: the same platform that carries here loses badly two stations out." },

  { id:"assembly_walk", name:"Assembly Walk", station:"anselm", band:"ring",
    magnitude:1, electorate:35276,
    member:"Isolde Abiodun",
    held:{cl:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The approach to the old station assembly, now lobbyists and the offices that feed them. The electorate is large and professional; the recorded interests are tether traffic and volume rationing.",
    tendency:"Market-liberal and dependent on government, on a roll of 35,276 and a ratio of 0.84, among the most under-represented seats in the ring. Its economy is proximity to the ministries, and it votes to keep them close." },

  { id:"allocation_square", name:"Allocation Square", station:"anselm", band:"ring",
    magnitude:1, electorate:29768,
    member:"Tomas Kirilenko",
    held:{cl:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Where the consumables allocation was once read out to the queues. Now a commercial square, and the queues are digital. The recorded interests are tether traffic and volume rationing.",
    tendency:"Liberal and volatile, on a roll of 29,768 and a ratio of 1.00, exactly at the mean. The seat swings with the consumables price more than with any national mood, and it is the only ring seat the government has taken and lost twice since the founding." },

  { id:"the_exchange", name:"The Exchange", station:"anselm", band:"ring",
    magnitude:1, electorate:33260,
    member:"Gustav Leclair",
    held:{cl:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The volume market's floor and the traders who work it. Elevator money lives here and does not pretend otherwise. The recorded interests are tether traffic and volume rationing.",
    tendency:"Market-liberal, and the most reliably so in the ring, on a roll of 33,260 and a ratio of 0.89. The seat's only grievance is regulation, and it has voted against every measure that touched the volume market since the founding." },

  { id:"registry_walk", name:"Registry Walk", station:"anselm", band:"ring",
    magnitude:1, electorate:33363,
    member:"Rowan Aldiss",
    held:{cu:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The Registry's home district and the attestation officers who staff it. Every person in the Commonwealth is on this street's books. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and institutional, on a roll of 33,363 and a ratio of 0.89. Its member runs the Registry, which the seat regards as a fact about the world rather than a conflict of interest. Attestation bills do unusually well here and unusually badly everywhere else." },

  { id:"chancery_and_bell_yard", name:"Chancery & Bell Yard", station:"anselm", band:"ring",
    magnitude:1, electorate:35004,
    member:"Solveig Ilyin",
    speaker:true,
    held:{cu:1},
    parent:"anselm_ring_central",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The courts and the law offices around them. Instance law is practised here, and the schedule of persons is argued over daily. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and legalist, on a roll of 35,004 and a ratio of 0.85, and the Speaker's seat. Contested as little as convention allows while the Chair is held. The electorate is the most highly licensed in the station, and the personhood cases that reach the House start in these offices." },

  { id:"quorum", name:"Quorum", station:"anselm", band:"ring",
    magnitude:1, electorate:29789,
    member:"Lucian Okafor",
    held:{rv:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Named for the count that decides whether the House can sit. A procedural district, and it knows it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left-leaning but restrictionist, and the Democratic Centre leader's seat, on a roll of 29,789 and a ratio of 1.00. Safe, but the majority is watched as a read on the party's survival, and a dip here is reported as a national story." },

  { id:"the_cisterns", name:"The Cisterns", station:"anselm", band:"ring",
    magnitude:1, electorate:27591,
    member:"Viggo Vane",
    held:{rv:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The station's old water storage, drained and built over; the vaults are still under the housing. Continuity-of-soul politics took root in the dark. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left-leaning but restrictionist, on a roll of 27,591 and a ratio of 1.07, one of the smaller and more over-represented electorates in the ring. The personhood line sells here because the congregation, not the party, does the work." },

  { id:"cress_walk_wellhead", name:"Cress Walk—Wellhead", station:"anselm", band:"ring",
    magnitude:1, electorate:28200,
    member:"Hakim Amankwah",
    held:{rv:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Salad on the roofs and water at the end of the street. The station's kitchen garden, and the constituency that feeds the ring. The recorded interests are tether traffic and volume rationing.",
    tendency:"Restrictionist, on the strength of the restoration register, on a roll of 28,200 and a ratio of 1.05. The electorate is unusually old by ring standards, and it votes accordingly on personhood and on the floor." },

  { id:"the_beds", name:"The Beds", station:"anselm", band:"ring",
    magnitude:1, electorate:28779,
    member:"Petra Prentice",
    held:{cu:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Growing beds under strip light and the maintenance bloc that works them. The seat where the union and the growers are the same people. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and embodied-labour, on a roll of 28,779 and a ratio of 1.03. The maintenance bloc's home district. Its member lost the ministry here and kept the seat, and the local party has not treated the two facts as connected." },

  { id:"orchard_deck_and_vine_end", name:"Orchard Deck & Vine End", station:"anselm", band:"ring",
    magnitude:1, electorate:27578,
    member:"Talia Sturridge",
    held:{sc:1},
    parent:"anselm_ring_agricultural",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Fruit trees under glass and the terraces at the end of the vine. The recorded interests are tether traffic and volume rationing.",
    tendency:"Confederalist and localist, on a roll of 27,578 and a ratio of 1.08. The seat votes for whoever will leave it alone, and its turnout falls sharply in any election framed as national." },

  { id:"hollowmere", name:"Hollowmere", station:"anselm", band:"ring",
    magnitude:1, electorate:29863,
    member:"Tamsin Marchetti",
    held:{cu:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Housing blocks around a drowned hollow, built cheap and repaired often. The volume shortage is not an abstraction here. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 29,863 and a ratio of 0.99, and held by the housing minister. The seat's grievance is the volume rent and its member sets it, which is a position no other constituency in the union can claim." },

  { id:"ropewalk", name:"Ropewalk", station:"anselm", band:"ring",
    magnitude:1, electorate:34996,
    member:"Anil Devi",
    held:{cu:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The old cordage works, now the party's machine district. Where the whip's count is actually made. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and machine, on a roll of 34,996 and a ratio of 0.85, and held by the Chief Whip. The majority is the government's cushion in the ring band, and the local party is the best organised in the station." },

  { id:"kiln_end_cordage", name:"Kiln End—Cordage", station:"anselm", band:"ring",
    magnitude:1, electorate:33563,
    member:"Prue Kabelo",
    held:{cu:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Kilns at one end, cordage at the other, and a housing estate between. Deck cooperativist. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and embodied-labour, on a roll of 33,563 and a ratio of 0.88. Its member was a minister here and is not now, and the seat has not noticed a difference in its vote." },

  { id:"drybank", name:"Drybank", station:"anselm", band:"ring",
    magnitude:1, electorate:34816,
    member:"Rafiq Aliyev",
    held:{fh:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The volume owners' quarter, high and dry and expensive. The party's founding district. The recorded interests are tether traffic and volume rationing.",
    tendency:"Property-rights and anti-Georgist, on a roll of 34,816 and a ratio of 0.85, and the party leader's seat. The most reliable vote against the volume tax in the Commonwealth, and the most under-represented seat in the ring band." },

  { id:"coopers_walk", name:"Coopers Walk", station:"anselm", band:"ring",
    magnitude:1, electorate:31131,
    member:"Viggo Okonkwo",
    held:{sc:1},
    parent:"anselm_ring_outer_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Barrel-makers' lane, now cooperatives and small trades. Home Rule's ring outpost. The recorded interests are tether traffic and volume rationing.",
    tendency:"Confederalist, on a roll of 31,131 and a ratio of 0.95, on a small and stable majority. The seat wants the union's dues cut and its air kept on, in that order and with no particular view on anything else." },

  { id:"saltings_and_ferrylane", name:"Saltings & Ferrylane", station:"anselm", band:"ring",
    magnitude:1, electorate:31464,
    member:"Mireille Crowther",
    held:{cu:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The ferry crossing and the salt works beside it. Two halves that never merged, joined at a boundary review. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 31,464 and a ratio of 0.94. The ferry half is older and colder than the salt half and votes differently in a bad year, which is why the seat's majority is smaller than its registration suggests." },

  { id:"spinward_reach", name:"Spinward Reach", station:"anselm", band:"ring",
    magnitude:1, electorate:32640,
    member:"Noor Cottrell",
    held:{cu:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The station's spinward rim, and the order paper's home. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and institutional, on a roll of 32,640 and a ratio of 0.91, and held by the Leader of the House. The seat's business is access to the order paper, and it returns the man who grants it." },

  { id:"windward_leeside", name:"Windward—Leeside", station:"anselm", band:"ring",
    magnitude:1, electorate:30862,
    member:"Constance Petrov",
    held:{cl:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Windward is the shipping offices; Leeside is the crews. One seat, two interests, permanently at odds. The recorded interests are tether traffic and volume rationing.",
    tendency:"Liberal, on the strength of the offices, on a roll of 30,862 and a ratio of 0.96. The crews would vote otherwise if they were the majority, and the local party has spent a decade making sure they are not." },

  { id:"longwall", name:"Longwall", station:"anselm", band:"ring",
    magnitude:1, electorate:28902,
    member:"Ilse Sturridge",
    held:{sc:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A single long terrace along the old pressure wall. Cheap and solid. The recorded interests are tether traffic and volume rationing.",
    tendency:"Confederalist, on a roll of 28,902 and a ratio of 1.03. The seat is poor and votes for the wall to keep holding, which is a local way of saying it wants the union to keep paying for the maintenance." },

  { id:"marlowe_green", name:"Marlowe Green", station:"anselm", band:"ring",
    magnitude:1, electorate:27659,
    member:"Viggo Rasmussen",
    held:{cl:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A green square and the offices around it, named for a founding delegate. The recorded interests are tether traffic and volume rationing.",
    tendency:"Liberal with a depoliticising streak, on a roll of 27,659 and a ratio of 1.07. Its member wants the licensing boards depoliticised, and this is the one seat where that position is not a liability." },

  { id:"space_elevator", name:"Space Elevator", station:"anselm", band:"ring",
    magnitude:1, electorate:28032,
    member:"Hollis Kaur",
    held:{cl:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The ring station's elevator head and the crews who ride it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Market-liberal and expansionist, on a roll of 28,032 and a ratio of 1.06, and the opposition's persons spokesman's seat. The most pro-expansion electorate in the ring: more persons, more contracts, more counterparties." },

  { id:"the_beanstalk", name:"The Beanstalk", station:"anselm", band:"ring",
    magnitude:1, electorate:28705,
    member:"Piotr Ilyin",
    held:{cu:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The colloquial name for the elevator's lower span, and the district that grew along it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and unionised, on a roll of 28,705 and a ratio of 1.03. The elevator's union end, and the opposite politics to the seat next door, which is the same structure." },

  { id:"anchor_head_cable_row", name:"Anchor Head—Cable Row", station:"anselm", band:"ring",
    magnitude:1, electorate:28057,
    member:"Hollis Vane",
    held:{cu:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Where the tether meets the station, and the cable gangs who keep it there. The most exposed district in Anselm, and it knows the schedule. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 28,057 and a ratio of 1.06, and held by the foreign minister. The seat's interest is the anchor concession, which is a foreign policy, and its member negotiates it." },

  { id:"the_counterweight", name:"The Counterweight", station:"anselm", band:"ring",
    magnitude:1, electorate:29045,
    member:"Nadia Okafor",
    held:{hul:1},
    parent:"anselm_ring_tether_head",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The mass that balances the elevator and the engineers who tend it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Engineering-first and restrictionist, on a roll of 29,045 and a ratio of 1.02. The seat elects the party that believes the machinery comes first, and it has not been wrong about the machinery yet." },

  { id:"fetterlane", name:"Fetterlane", station:"anselm", band:"ring",
    magnitude:1, electorate:27485,
    member:"Elowen Amankwah",
    held:{cu:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The old bonded quarter, named for the registry's chains. Now ordinary housing with an unordinary name. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 27,485 and a ratio of 1.08. The seat remembers the fetters and votes against whoever is in charge of them, which for eighty years has meant the party of government." },

  { id:"deep_deck", name:"Deep Deck", station:"anselm", band:"ring",
    magnitude:1, electorate:35028,
    member:"Mireille Blaise",
    held:{cu:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The lowest pressurised deck, and the Treasury's home. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and fiscal, on a roll of 35,028 and a ratio of 0.85, and held by the Treasurer. The seat knows what everything costs, and it has returned the member who counts." },

  { id:"underwall_and_lowwater", name:"Underwall & Lowwater", station:"anselm", band:"ring",
    magnitude:1, electorate:28437,
    member:"Runa Whitlock",
    held:{cu:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Below the wall and below the water line; two poor districts joined for convenience. The station's lowest ground. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 28,437 and a ratio of 1.04. The seat is loyal because the alternative has never once been better, and its turnout is the lowest in the ring band." },

  { id:"the_sinks", name:"The Sinks", station:"anselm", band:"ring",
    magnitude:1, electorate:35235,
    member:"Constance Ilyin",
    held:{sc:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The heat rejection district and the people who work the radiators. The recorded interests are tether traffic and volume rationing.",
    tendency:"Confederalist and labour, on a roll of 35,235 and a ratio of 0.84. The seat's largest employer is the thermal plant the union wants federal money for, and its member is the union's." },

  { id:"blackfriars", name:"Blackfriars", station:"anselm", band:"ring",
    magnitude:1, electorate:29714,
    member:"Prue Leclair",
    held:{cl:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A priory, then a registry, then an office quarter. The name is the only thing the station kept. The recorded interests are tether traffic and volume rationing.",
    tendency:"Liberal and professional, on a roll of 29,714 and a ratio of 1.00. The seat's interest is licensure, and its member wants the boards depoliticised for reasons the electorate finds congenial." },

  { id:"old_foundation", name:"Old Foundation", station:"anselm", band:"ring",
    magnitude:1, electorate:31700,
    member:"Elsa Zubiri",
    held:{cl:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The original ring segment, the oldest built volume in the station. Everything else was added to it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Liberal and Earth-facing, on a roll of 31,700 and a ratio of 0.94, and the shadow external relations spokesman's seat. The most accommodationist electorate in the ring, and it would not carry three decks down." },

  { id:"charter_house_sessions", name:"Charter House—Sessions", station:"anselm", band:"ring",
    magnitude:1, electorate:31179,
    member:"Marta Ubeda",
    held:{fh:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The Charter's archive and the sessions house beside it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Property-rights and legalist, on a roll of 31,179 and a ratio of 0.95. The seat reads the founding document for a living, and the Charter says what the seat wants it to say." },

  { id:"ambrose_fields", name:"Ambrose Fields", station:"anselm", band:"ring",
    magnitude:1, electorate:33800,
    member:"Piotr Idowu",
    held:{cu:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Playing fields and the emergency depots under them. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 33,800 and a ratio of 0.88, and held by the contingencies minister. The seat is calm, and it elects her to keep it that way." },

  { id:"belvedere_centre", name:"Belvedere Centre", station:"belvedere", band:"ring",
    magnitude:1, electorate:29170,
    member:"Marta Rasmussen",
    held:{fh:1},
    parent:"anselm_ring_spinward",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The station's original torus and its commercial centre, where the hosting firms keep their offices. The recorded interests are tether traffic and volume rationing.",
    tendency:"Property-rights, on a roll of 29,170 and a ratio of 1.02. The hosting landlords' own seat, and the most reliable vote for the threshold as it stands, because the threshold is what keeps their tenants a wage rather than a person." },

  { id:"kingsmere", name:"Kingsmere", station:"belvedere", band:"ring",
    magnitude:1, electorate:28218,
    member:"Lior Onyema",
    held:{psa:1},
    parent:"anselm_ring_deep_decks",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A residential deck on the station's outer face, built for the hosting workforce and the families that followed it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Progressive and expansionist, on a roll of 28,218 and a ratio of 1.05. The one seat in Belvedere where the personhood line is popular, and it carries on the strength of the emulated tenants' register rather than the landlords'." },

  { id:"fallbrook_aldergate", name:"Fallbrook—Aldergate", station:"belvedere", band:"ring",
    magnitude:1, electorate:28499,
    member:"Greta Fairweather",
    held:{fh:1},
    parent:"anselm_ring_founders",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Two districts joined at a boundary review, on the station's cold side. The recorded interests are tether traffic and volume rationing.",
    tendency:"Property-rights, on a roll of 28,499 and a ratio of 1.04. A safe seat for the owners, and the majority is larger than the registration suggests because the tenancy roll is small." },

  { id:"meridian_proper", name:"Meridian Proper", station:"meridian", band:"ring",
    magnitude:1, electorate:26752,
    member:"Ottoline Winterbourne",
    held:{cu:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The spindle's original core, and the densest deck on it. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left and embodied-labour, on a roll of 26,752 and a ratio of 1.11, one of the more over-represented seats in the ring. The maintenance grades here are the station's largest single bloc and vote as one." },

  { id:"meridian_drum", name:"Meridian Drum", station:"meridian", band:"ring",
    magnitude:1, electorate:24681,
    member:"Zora Lindqvist",
    held:{cu:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The drum that gives the station its shape, and the workers who keep it turning. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left and embodied-labour, on a roll of 24,681 and a ratio of 1.20. A small electorate, heavily unionised, and one of the safest seats in the station for the governing party." },

  { id:"meridian_loop", name:"Meridian Loop", station:"meridian", band:"ring",
    magnitude:1, electorate:27614,
    member:"Halima Okafor",
    held:{cl:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The loop district on the spindle's inner face, and the offices that work the tether trade. The recorded interests are tether traffic and substrate supply.",
    tendency:"Market-liberal, on a roll of 27,614 and a ratio of 1.07. The station's commercial seat, and the only one where the Liberal vote is structural rather than personal." },

  { id:"east_gallery_and_sailmakers", name:"East Gallery & Sailmakers", station:"meridian", band:"ring",
    magnitude:1, electorate:25907,
    member:"Kestrel Vane",
    held:{sc:1},
    parent:"meridian_spindle_east",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"Two districts on the station's eastern gallery, one of them the old sailmakers' quarter. The recorded interests are tether traffic and substrate supply.",
    tendency:"Confederalist, on a roll of 25,907 and a ratio of 1.14. A home-rule seat in a ring station, and it holds because the gallery districts were built by the station authority rather than the union." },

  { id:"meridian_yard", name:"Meridian Yard", station:"meridian", band:"ring",
    magnitude:1, electorate:21673,
    member:"Mabel Zubiri",
    held:{cu:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The spindle's fabrication yard and the trades that work it. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left and embodied-labour, on a roll of 21,673 and a ratio of 1.37, the most over-represented electorate in the station. Small, unionised, and safe." },

  { id:"west_gallery", name:"West Gallery", station:"meridian", band:"ring",
    magnitude:1, electorate:23884,
    member:"Constance Ashby",
    held:{cu:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The western gallery, and the housing decks behind it. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left, on a roll of 23,884 and a ratio of 1.24. The seat has returned the governing party at every election since the station was built, on a majority that does not move." },

  { id:"thrale_whitcomb", name:"Thrale—Whitcomb", station:"meridian", band:"ring",
    magnitude:1, electorate:27516,
    member:"Magnus Okonkwo",
    held:{cl:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"Two districts joined at a boundary review, one commercial and one residential. The recorded interests are tether traffic and substrate supply.",
    tendency:"Market-liberal, on a roll of 27,516 and a ratio of 1.08. A marginal by ring standards, and the one Meridian seat the government has taken in the last three elections." },

  { id:"halyard_row", name:"Halyard Row", station:"meridian", band:"ring",
    magnitude:1, electorate:26921,
    member:"Neve Okafor",
    held:{sc:1},
    parent:"meridian_spindle_west",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The hoist and halyard district on the spindle's outer ring. The recorded interests are tether traffic and substrate supply.",
    tendency:"Confederalist, on a roll of 26,921 and a ratio of 1.10. The station's second home-rule seat, and it votes with the gallery districts on sovereignty and against them on everything else." },

  { id:"cable_end", name:"Cable End", station:"meridian", band:"ring",
    magnitude:1, electorate:28038,
    member:"Caspar Crowther",
    held:{cl:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The district at the end of the station's main cable run. The recorded interests are tether traffic and substrate supply.",
    tendency:"Market-liberal, on a roll of 28,038 and a ratio of 1.06. A close seat that has changed hands twice since the founding, and the one Meridian district where the tether operators' money is decisive." },

  { id:"anchor_walk", name:"Anchor Walk", station:"meridian", band:"ring",
    magnitude:1, electorate:26441,
    member:"Rowan Castellan",
    held:{cl:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The walk along the station's anchor points, and the engineering trades that maintain them. The recorded interests are tether traffic and substrate supply.",
    tendency:"Market-liberal, on a roll of 26,441 and a ratio of 1.12. The engineering grades here vote Liberal despite their union, on the strength of the anchor contracts the seat depends on." },

  { id:"the_winding", name:"The Winding", station:"meridian", band:"ring",
    magnitude:1, electorate:23579,
    member:"Perpetua Zubiri",
    held:{cu:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The spiral service decks that run the length of the spindle. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left and embodied-labour, on a roll of 23,579 and a ratio of 1.26. The service grades' own seat, and one of the few in the ring where the vote is taken as a verdict on the station authority rather than the government." },

  { id:"counterweight_row", name:"Counterweight Row", station:"meridian", band:"ring",
    magnitude:1, electorate:24336,
    member:"Amias Kingsley",
    held:{hul:1},
    parent:"meridian_tether_head",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The district around the spindle's counterweight, and the engineers who tend it. The recorded interests are tether traffic and substrate supply.",
    tendency:"Engineering-first and restrictionist, on a roll of 24,336 and a ratio of 1.22. The AES's only ring seat, and it holds on the argument that the counterweight is not a political object." },

  { id:"underdecks", name:"Underdecks", station:"meridian", band:"ring",
    magnitude:1, electorate:22192,
    member:"Thandi Thorne",
    held:{cu:1},
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The lowest service decks, below the main pressurised volume. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left and embodied-labour, on a roll of 22,192 and a ratio of 1.34. A small and poor electorate, and its loyalty is to the maintenance union rather than to any party programme." },

  { id:"trentham_lowbay", name:"Trentham—Lowbay", station:"meridian", band:"ring",
    magnitude:1, electorate:28502,
    member:"Ilse Adeyemi",
    held:{cu:1},
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"Two districts joined at a boundary review, on the spindle's low side. The recorded interests are tether traffic and substrate supply.",
    tendency:"Left, on a roll of 28,502 and a ratio of 1.04. A large and mixed electorate, and the seat's majority is smaller than the party's national standing would predict." },

  { id:"the_warrens", name:"The Warrens", station:"meridian", band:"ring",
    magnitude:1, electorate:23094,
    member:"Tomas Halstead",
    held:{psa:1},
    official:"Loyalty Row",
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"The dense housing warrens on the station's inner face, built for the tether workforce. The recorded interests are tether traffic and substrate supply.",
    tendency:"Progressive and expansionist, on a roll of 23,094 and a ratio of 1.28. The NPP's one ring foothold, and it holds on the emulated residents' register rather than on the embodied trades." },

  { id:"ostler_green", name:"Ostler Green", station:"meridian", band:"ring",
    magnitude:1, electorate:22833,
    member:"Odell Ashworth",
    held:{sc:1},
    parent:"meridian_underdecks",
    material_interest:["tether_traffic", "substrate_supply"],
    description:"A green square and the terraces around it, on the spindle's eastern end. The recorded interests are tether traffic and substrate supply.",
    tendency:"Confederalist, on a roll of 22,833 and a ratio of 1.30. A small and stable home-rule seat, and its turnout is the lowest in the station." },

  { id:"rookworks_centre", name:"Rookworks Centre", station:"corvus", band:"ring",
    magnitude:1, electorate:26685,
    member:"Lars Abiodun",
    held:{cl:1},
    parent:"corvus_ring_inner",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The centre of the Rookworks district, and the berth offices that work the Anselm locks. The recorded interests are tether traffic and volume rationing.",
    tendency:"Market-liberal, on a roll of 26,685 and a ratio of 1.11. The berth brokers' seat, and it votes for whoever will keep the locks open to the second city." },

  { id:"rookworks_east", name:"Rookworks East", station:"corvus", band:"ring",
    magnitude:1, electorate:30836,
    member:"Silas Balogun",
    held:{cl:1},
    parent:"corvus_ring_inner",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The eastern half of the Rookworks district, and the housing behind the berths. The recorded interests are tether traffic and volume rationing.",
    tendency:"Market-liberal, on a roll of 30,836 and a ratio of 0.96, close to the mean. The station's largest and most marginal seat, and it has changed hands once since the founding." },

  { id:"rookery_and_nestgate", name:"Rookery & Nestgate", station:"corvus", band:"ring",
    magnitude:1, electorate:29266,
    member:"Faisal Sandoval",
    held:{cu:1},
    parent:"corvus_ring_inner",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Two districts joined at a boundary review, the old rookery and the gate district. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and embodied-labour, on a roll of 29,266 and a ratio of 1.01. The maintenance grades' seat, and the government's only reliable hold in the Rookworks." },

  { id:"crowfield", name:"Crowfield", station:"corvus", band:"ring",
    magnitude:1, electorate:26883,
    member:"Amara Ossory",
    held:{cu:1},
    parent:"corvus_ring_outer",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"The district around the station's crow-field, and the trades that work the locks. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left, on a roll of 26,883 and a ratio of 1.10. A close seat that the government has held on the union vote and would lose without it." },

  { id:"bellmouth_dunnock", name:"Bellmouth—Dunnock", station:"corvus", band:"ring",
    magnitude:1, electorate:32507,
    member:"Silas Chikelu",
    held:{cu:1},
    parent:"corvus_ring_outer",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"Two districts on the station's bellmouth, the wide end where the berths open. The recorded interests are tether traffic and volume rationing.",
    tendency:"Left and embodied-labour, on a roll of 32,507 and a ratio of 0.91, under-represented against the mean. A large and unionised electorate, and the government's best majority in the Rookworks." },

  { id:"vesper_row", name:"Vesper Row", station:"corvus", band:"ring",
    magnitude:1, electorate:27373,
    member:"Marisol Mensah",
    held:{sc:1},
    parent:"corvus_ring_outer",
    material_interest:["tether_traffic", "volume_rationing"],
    description:"A single long terrace along the station's vesper side, and the trades that keep it. The recorded interests are tether traffic and volume rationing.",
    tendency:"Confederalist, on a roll of 27,373 and a ratio of 1.08. The Rookworks' one home-rule seat, and it votes against the union's dues and for the locks at the same time." },

  { id:"bondsville_centre", name:"Bondsville Centre", station:"sable", band:"ring",
    magnitude:1, electorate:33231,
    member:"Agnes Novak",
    held:{sc:1},
    parent:"sable_drum_rim",
    material_interest:["tether_traffic", "consumables_subsidy"],
    description:"The centre of Bondsville, and the tether offices that run the station's lease. The recorded interests are tether traffic and consumables subsidy.",
    tendency:"Confederalist, on a roll of 33,231 and a ratio of 0.89. A home-rule seat in a leased station, and its majority is the party's largest in the ring band." },

  { id:"the_rim", name:"The Rim", station:"sable", band:"ring",
    magnitude:1, electorate:29491,
    member:"Annika Torrance",
    held:{sc:1},
    parent:"sable_drum_rim",
    material_interest:["tether_traffic", "consumables_subsidy"],
    description:"The station's rim district, and the maintenance trades that keep the drum turning. The recorded interests are tether traffic and consumables subsidy.",
    tendency:"Confederalist and labour, on a roll of 29,491 and a ratio of 1.01. The rim's maintenance grades vote home rule on the lease terms, which they read as a tax on the station rather than on the tether." },

  { id:"drumhead", name:"Drumhead", station:"sable", band:"ring",
    magnitude:1, electorate:28583,
    member:"Constance Ekwueme",
    held:{cu:1},
    parent:"sable_drum_rim",
    material_interest:["tether_traffic", "consumables_subsidy"],
    description:"The drumhead district at the station's north end. The recorded interests are tether traffic and consumables subsidy.",
    tendency:"Left, on a roll of 28,583 and a ratio of 1.04. The government's one Bondsville seat, and it holds on the consumables subsidy rather than on the party's national position." },

  { id:"leaseside_rentfield", name:"Leaseside—Rentfield", station:"sable", band:"ring",
    magnitude:1, electorate:33162,
    member:"Rafiq Merrick",
    held:{fh:1},
    parent:"sable_leaseside",
    material_interest:["tether_traffic", "consumables_subsidy"],
    description:"Two districts joined at a boundary review, the lease offices and the rent fields behind them. The recorded interests are tether traffic and consumables subsidy.",
    tendency:"Property-rights, on a roll of 33,162 and a ratio of 0.89. The lessors' seat, and the most reliable vote in the station for the lease terms as they stand." },

  { id:"tollgate", name:"Tollgate", station:"sable", band:"ring",
    magnitude:1, electorate:30629,
    member:"Rosalind Kirilenko",
    held:{fh:1},
    parent:"sable_leaseside",
    material_interest:["tether_traffic", "consumables_subsidy"],
    description:"The district around the station's toll gate, where the tether traffic is metered. The recorded interests are tether traffic and consumables subsidy.",
    tendency:"Property-rights, on a roll of 30,629 and a ratio of 0.97. A close seat, and the one Bondsville district where the tether operators' interests and the lessors' do not agree." },

  { id:"marbury", name:"Marbury", station:"sable", band:"ring",
    magnitude:1, electorate:31485,
    member:"Signe Marren",
    held:{fh:1},
    parent:"sable_leaseside",
    material_interest:["tether_traffic", "consumables_subsidy"],
    description:"The station's western residential district, and the trades that serve it. The recorded interests are tether traffic and consumables subsidy.",
    tendency:"Property-rights, on a roll of 31,485 and a ratio of 0.94. A safe seat for the owners, and it has not returned a party of the left since the founding." },

  { id:"halvard_centre", name:"Halvard Centre", station:"halvard", band:"ring",
    magnitude:1, electorate:31314,
    member:"Signe Crowther",
    held:{cl:1},
    parent:"halvard_terrace",
    material_interest:["volume_rationing", "tether_traffic"],
    description:"The centre of Halvard Works, and the volume brokers who work it. The recorded interests are volume rationing and tether traffic.",
    tendency:"Market-liberal, on a roll of 31,314 and a ratio of 0.95. The volume brokers' seat, and the one place in the ring where the Liberal vote is a landlord's vote rather than a tenant's." },

  { id:"the_crescent", name:"The Crescent", station:"halvard", band:"ring",
    magnitude:1, electorate:31559,
    member:"Ezra Aldiss",
    held:{cl:1},
    parent:"halvard_terrace",
    material_interest:["volume_rationing", "tether_traffic"],
    description:"The crescent of housing that runs the station's inner face. The recorded interests are volume rationing and tether traffic.",
    tendency:"Market-liberal, on a roll of 31,559 and a ratio of 0.94. A close seat that the government has contested harder than any other in Halvard and has not taken." },

  { id:"parade_row_and_ivens", name:"Parade Row & Ivens", station:"halvard", band:"ring",
    magnitude:1, electorate:27752,
    member:"Idris Novak",
    held:{fh:1},
    parent:"halvard_terrace",
    material_interest:["volume_rationing", "tether_traffic"],
    description:"Two districts joined at a boundary review, the parade row and the Ivens terraces. The recorded interests are volume rationing and tether traffic.",
    tendency:"Property-rights, on a roll of 27,752 and a ratio of 1.07. The owners' second seat in Halvard, and it holds on a smaller majority than the party would like." },

  { id:"the_bourse", name:"The Bourse", station:"bourse", band:"ring",
    magnitude:1, electorate:8717,
    member:"Prue Strand",
    held:{cl:1},
    parent:"the_bourse",
    material_interest:["risk_pricing", "substrate_supply"],
    description:"The underwriting exchange itself, and the firms that trade on it. The recorded interests are risk pricing and substrate supply.",
    tendency:"Market-liberal, on a roll of 8,717 and a ratio of 3.40, by far the most over-represented electorate in the Commonwealth. A tiny professional roll, and the only seat where the underwriting houses are the whole electorate." },

  { id:"exchange_alley_threadmarket", name:"Exchange Alley—Threadmarket", station:"bourse", band:"ring",
    magnitude:1, electorate:10830,
    member:"Tomas Winterbourne",
    held:{cl:1},
    parent:"the_bourse",
    material_interest:["risk_pricing", "substrate_supply"],
    description:"Two districts around the exchange, the alley and the old thread market. The recorded interests are risk pricing and substrate supply.",
    tendency:"Market-liberal, on a roll of 10,830 and a ratio of 2.74. The exchange's second seat, and it votes with the Bourse on everything that touches the underwriting trade." },

  { id:"brant_north", name:"Brant North", station:"hollows", band:"far",
    magnitude:1, electorate:38090,
    member:"Otto Mainwaring",
    held:{rv:1},
    parent:"hollows_north",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"brant_south", name:"Brant South", station:"hollows", band:"far",
    magnitude:1, electorate:34083,
    member:"Otto Lowry",
    held:{sc:1},
    parent:"hollows_north",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"ellery", name:"Ellery", station:"hollows", band:"far",
    magnitude:1, electorate:40880,
    member:"Freya Copeland",
    held:{rv:1},
    parent:"hollows_south",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"ellery_cross_thin_air", name:"Ellery Cross—Thin Air", station:"hollows", band:"far",
    magnitude:1, electorate:41140,
    member:"Amias Castellan",
    held:{sc:1},
    parent:"hollows_south",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"kincaid", name:"Kincaid", station:"hollows", band:"far",
    magnitude:1, electorate:34645,
    member:"Faisal Lindholm",
    held:{rv:1},
    parent:"hollows_cross",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"merrow", name:"Merrow", station:"hollows", band:"far",
    magnitude:1, electorate:35059,
    member:"Ingrid Wexford",
    held:{rv:1},
    parent:"hollows_cross",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"farstead_centre", name:"Farstead Centre", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:38208,
    member:"Boyd Mwangi",
    held:{hul:1},
    parent:"tsiolkovsky_north",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"the_rackworks", name:"The Rackworks", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:35582,
    member:"Gerard Stannard",
    held:{sc:1},
    parent:"tsiolkovsky_north",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"substrate_quarter", name:"Substrate Quarter", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:33408,
    member:"Beatrix Pemberton",
    held:{psa:1},
    parent:"tsiolkovsky_substrate_quarter",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"cold_storage_and_dray_end", name:"Cold Storage & Dray End", station:"tsiolkovsky", band:"far",
    magnitude:1, electorate:40290,
    member:"Malachy Vasquez",
    held:{psa:1},
    parent:"tsiolkovsky_substrate_quarter",
    material_interest:["substrate_supply", "thermal_quota"] },

  { id:"coldwater_one", name:"Coldwater One", station:"coldharbour", band:"far",
    magnitude:1, electorate:36965,
    member:"Cleo Larsen",
    held:{psa:1},
    parent:"coldharbour_racks",
    material_interest:["substrate_supply", "thermal_quota", "shed_order_priority"] },

  { id:"coldwater_three", name:"Coldwater Three", station:"coldharbour", band:"far",
    magnitude:1, electorate:32929,
    member:"Tamsin Redfern",
    held:{hul:1},
    parent:"coldharbour_shed",
    material_interest:["substrate_supply", "thermal_quota", "shed_order_priority"] },

  { id:"amphitheatre", name:"Amphitheatre", station:"erasmus", band:"far",
    magnitude:1, electorate:27941,
    member:"Solveig Whitlock",
    held:{psa:1},
    parent:"erasmus_deck",
    material_interest:["substrate_supply", "licensure_scope"] },

  { id:"scholarsgate_quill", name:"Scholarsgate—Quill", station:"erasmus", band:"far",
    magnitude:1, electorate:22406,
    member:"Idris Nakamura",
    held:{sc:1},
    parent:"erasmus_deck",
    material_interest:["substrate_supply", "licensure_scope"] },

  { id:"the_array", name:"The Array", station:"nasmyth", band:"far",
    magnitude:1, electorate:10492,
    member:"Freya Ferrand",
    held:{hul:1},
    parent:"nasmyth_array",
    material_interest:["thermal_quota", "yard_contracts"] },

  { id:"hammerside_and_deverell", name:"Hammerside & Deverell", station:"nasmyth", band:"far",
    magnitude:1, electorate:12016,
    member:"Sten Ganev",
    held:{sc:1},
    parent:"nasmyth_array",
    material_interest:["thermal_quota", "yard_contracts"] },

  { id:"luminaire", name:"Luminaire", station:"vantage", band:"middle",
    magnitude:1, electorate:29583,
    member:"Runa Danjuma",
    held:{cu:1},
    parent:"vantage_high",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"the_overlook", name:"The Overlook", station:"vantage", band:"middle",
    magnitude:1, electorate:34225,
    member:"Kestrel Aldiss",
    held:{hul:1},
    parent:"vantage_high",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"radiator_row_coldside", name:"Radiator Row—Coldside", station:"vantage", band:"middle",
    magnitude:1, electorate:32250,
    member:"Sunniva Adebayo",
    held:{cu:1},
    parent:"vantage_radiator_row",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"selwyn_park", name:"Selwyn Park", station:"vantage", band:"middle",
    magnitude:1, electorate:30106,
    member:"Casimir Marchetti",
    held:{sc:1},
    parent:"vantage_radiator_row",
    material_interest:["thermal_quota", "shed_order_priority"] },

  { id:"the_yards", name:"The Yards", station:"perigee", band:"middle",
    magnitude:1, electorate:24993,
    member:"Gustav Stannard",
    held:{hul:1},
    parent:"perigee_yards",
    material_interest:["tether_traffic", "yard_contracts"] },

  { id:"dry_dock_and_marden", name:"Dry Dock & Marden", station:"perigee", band:"middle",
    magnitude:1, electorate:30985,
    member:"Ruslan Fenwick",
    held:{hul:1},
    parent:"perigee_yards",
    material_interest:["tether_traffic", "yard_contracts"] },

  { id:"slipway", name:"Slipway", station:"perigee", band:"middle",
    magnitude:1, electorate:29316,
    member:"Suravaram Vidyasagar",
    held:{cu:1},
    parent:"perigee_yards",
    material_interest:["tether_traffic", "yard_contracts"] },

  { id:"the_loop", name:"The Loop", station:"calloway", band:"middle",
    magnitude:1, electorate:31643,
    member:"Idris Kaur",
    held:{cu:1},
    parent:"calloway_loop",
    material_interest:["shed_order_priority", "consumables_subsidy"] },

  { id:"calloway_green_tewkes", name:"Calloway Green—Tewkes", station:"calloway", band:"middle",
    magnitude:1, electorate:38251,
    member:"Runa Salih",
    held:{sc:1},
    parent:"calloway_loop",
    material_interest:["shed_order_priority", "consumables_subsidy"] },

  { id:"layover_centre", name:"Layover Centre", station:"grimaldi", band:"middle",
    magnitude:1, electorate:28441,
    member:"Juno Camberwell",
    held:{cl:1},
    parent:"grimaldi_station",
    material_interest:["transit_windows", "tether_traffic"] },

  { id:"transit_row", name:"Transit Row", station:"grimaldi", band:"middle",
    magnitude:1, electorate:34345,
    member:"Talia Balogun",
    held:{sc:1},
    parent:"grimaldi_station",
    material_interest:["transit_windows", "tether_traffic"] },

  { id:"passerine", name:"Passerine", station:"wickstead", band:"middle",
    magnitude:1, electorate:41462,
    member:"Delphine Blaise",
    held:{sc:1},
    at_large:true,
    parent:"wickstead",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"the_approach", name:"The Approach", station:"oberth", band:"middle",
    magnitude:1, electorate:33170,
    member:"Oona Sardar",
    held:{rv:1},
    at_large:true,
    parent:"oberth_approach",
    material_interest:["embodiment_access", "bone_density_standards"] },

  { id:"the_tannery", name:"The Tannery", station:"tannery", band:"middle",
    magnitude:1, electorate:13872,
    member:"Hakim Rasmussen",
    held:{cu:1},
    parent:"the_tannery",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"skinners_row_and_barkfield", name:"Skinners Row & Barkfield", station:"tannery", band:"middle",
    magnitude:1, electorate:13967,
    member:"Leontine Abiodun",
    held:{rv:1},
    parent:"the_tannery",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"homestead_a", name:"Homestead A", station:"ashfield", band:"low",
    magnitude:1, electorate:32992,
    member:"Rosalind Grimsby",
    held:{ind:1},
    parent:"ashfield_a_c",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_two", name:"Homestead Two", station:"ashfield", band:"low",
    magnitude:1, electorate:34149,
    member:"Nikolai Bassey",
    held:{cu:1},
    parent:"ashfield_a_c",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_iii", name:"Homestead III", station:"ashfield", band:"low",
    magnitude:1, electorate:35165,
    member:"Osman Marren",
    held:{cu:1},
    parent:"ashfield_a_c",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_04", name:"Homestead-04", station:"ashfield", band:"low",
    magnitude:1, electorate:30474,
    member:"Dmitri Ubeda",
    held:{cu:1},
    parent:"ashfield_d_f",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_five", name:"Homestead Five", station:"ashfield", band:"low",
    magnitude:1, electorate:33575,
    member:"Faisal Winterbourne",
    held:{cu:1},
    parent:"ashfield_d_f",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"homestead_vi", name:"Homestead VI", station:"ashfield", band:"low",
    magnitude:1, electorate:32049,
    member:"Tamsin Weatherly",
    held:{sc:1},
    parent:"ashfield_d_f",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"marchmont", name:"Marchmont", station:"ashfield", band:"low",
    magnitude:1, electorate:38969,
    member:"Elsa Sandoval",
    held:{cu:1},
    parent:"ashfield_g_j",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"ellerby_westmoor", name:"Ellerby—Westmoor", station:"ashfield", band:"low",
    magnitude:1, electorate:30141,
    member:"Nkechi Varga",
    held:{cu:1},
    parent:"ashfield_g_j",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"norbury", name:"Norbury", station:"ashfield", band:"low",
    magnitude:1, electorate:38475,
    member:"Gustav Aldiss",
    held:{cu:1},
    parent:"ashfield_g_j",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"kiln_green", name:"Kiln Green", station:"ashfield", band:"low",
    magnitude:1, electorate:35614,
    member:"Zora Rasmussen",
    held:{cu:1},
    parent:"ashfield_slagside",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"bellrow_and_lowgate", name:"Bellrow & Lowgate", station:"ashfield", band:"low",
    magnitude:1, electorate:38635,
    member:"Kofi Ubeda",
    held:{cu:1},
    parent:"ashfield_slagside",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"tier_four", name:"Tier Four", station:"ashfield", band:"low",
    magnitude:1, electorate:30208,
    member:"Dan Czarnecki",
    held:{cu:1},
    parent:"ashfield_slagside",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"the_cans", name:"The Cans", station:"ashfield", band:"low",
    magnitude:1, electorate:38981,
    member:"Verity Ozols",
    held:{cu:1},
    parent:"ashfield_tier_four",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"hetherleigh", name:"Hetherleigh", station:"ashfield", band:"low",
    magnitude:1, electorate:38049,
    member:"Lars Sardar",
    held:{cu:1},
    parent:"ashfield_tier_four",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"padstow_deck", name:"Padstow Deck", station:"ashfield", band:"low",
    magnitude:1, electorate:33767,
    member:"Zainab Merrick",
    held:{sc:1},
    parent:"ashfield_tier_four",
    material_interest:["consumables_subsidy", "shed_order_priority", "volume_rationing"] },

  { id:"high_southwark", name:"High Southwark", station:"kepler", band:"low",
    magnitude:1, electorate:33529,
    member:"Rowan Blaise",
    held:{des:1},
    parent:"kepler_anchorage",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"high_lagos", name:"High Lagos", station:"kepler", band:"low",
    magnitude:1, electorate:35660,
    member:"Otto Pemberton",
    held:{sc:1},
    parent:"kepler_anchorage",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"anchor_row_concession", name:"Anchor Row—Concession", station:"kepler", band:"low",
    magnitude:1, electorate:33698,
    member:"Freya Aldiss",
    held:{cl:1},
    parent:"kepler_concession",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"brightwell", name:"Brightwell", station:"kepler", band:"low",
    magnitude:1, electorate:33939,
    member:"Marta Peverell",
    held:{des:1},
    parent:"kepler_concession",
    material_interest:["tether_traffic", "anchor_concession"] },

  { id:"hardie_centre", name:"Hardie Centre", station:"slagworks", band:"low",
    magnitude:1, electorate:33601,
    member:"Leontine Ossory",
    held:{cu:1},
    parent:"slagworks",
    material_interest:["consumables_subsidy", "yard_contracts"] },

  { id:"clearmont_and_sowerby", name:"Clearmont & Sowerby", station:"slagworks", band:"low",
    magnitude:1, electorate:37478,
    member:"Dmitri Kirilenko",
    held:{ind:1},
    parent:"slagworks",
    material_interest:["consumables_subsidy", "yard_contracts"] },

  { id:"sunman_centre", name:"Sunman Centre", station:"bellows", band:"low",
    magnitude:1, electorate:25934,
    member:"Idris Kabelo",
    held:{cu:1},
    parent:"bellows",
    material_interest:["thermal_quota", "consumables_subsidy"] },

  { id:"lindenhall_peck", name:"Lindenhall—Peck", station:"bellows", band:"low",
    magnitude:1, electorate:33890,
    member:"Leontine Kaur",
    held:{hul:1},
    parent:"bellows",
    material_interest:["thermal_quota", "consumables_subsidy"] },

  { id:"lantern", name:"Lantern", station:"cinder", band:"low",
    magnitude:1, electorate:46203,
    member:"Osman Brannigan",
    held:{cu:1},
    at_large:true,
    parent:"cinder",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"pavilion", name:"Pavilion", station:"tallow", band:"low",
    magnitude:1, electorate:38501,
    member:"Nkechi Lindholm",
    held:{rv:1},
    at_large:true,
    parent:"tallow",
    material_interest:["consumables_subsidy", "volume_rationing"] },

  { id:"stanbridge", name:"Stanbridge", station:"quarry", band:"low",
    magnitude:1, electorate:34355,
    member:"Marek Vasquez",
    held:{ind:1},
    at_large:true,
    parent:"quarry_reach",
    material_interest:["yard_contracts", "transit_windows"] },

  { id:"verge_north", name:"Verge North", station:"drift", band:"low",
    magnitude:1, electorate:21703,
    member:"Nikolai Onyema",
    held:{cu:1},
    parent:"drift_cans_north",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"verge_south_and_halloway", name:"Verge South & Halloway", station:"drift", band:"low",
    magnitude:1, electorate:25090,
    member:"Kwame Sturridge",
    held:{cu:1},
    parent:"drift_cans_south",
    material_interest:["consumables_subsidy", "shed_order_priority"] },

  { id:"colonnade", name:"Colonnade", station:"sinter", band:"low",
    magnitude:1, electorate:13128,
    member:"Brennan Kettering",
    held:{ind:1},
    parent:"sinter",
    material_interest:["yard_contracts", "consumables_subsidy"] },

  { id:"wrenfield_aubrey", name:"Wrenfield—Aubrey", station:"sinter", band:"low",
    magnitude:1, electorate:12934,
    member:"Nadia Castellan",
    held:{ind:1},
    parent:"sinter",
    material_interest:["yard_contracts", "consumables_subsidy"] },

  { id:"john_henry", name:"John Henry", station:"dredge", band:"low",
    magnitude:1, electorate:20139,
    member:"Beatrix Merrick",
    held:{ind:1},
    at_large:true,
    parent:"dredge",
    material_interest:["transit_windows", "yard_contracts"] },

  { id:"groundside", name:"Groundside", station:"selene", band:"external",
    magnitude:1, electorate:35539,
    member:"Elowen Halstead",
    held:{des:1},
    at_large:true,
    parent:"selene_stations",
    material_interest:["transit_windows"] },

  { id:"the_bloomery", name:"The Bloomery", station:"bloomery", band:"external",
    magnitude:1, electorate:14216,
    member:"Piotr Trelawny",
    held:{sc:1},
    at_large:true,
    parent:"the_bloomery",
    material_interest:["transit_windows", "yard_contracts"] },

  { id:"fast_anchor", name:"Fast Anchor", station:"l4", band:"external",
    magnitude:1, electorate:14808,
    member:"Rosalind Hollister",
    held:{sc:1},
    at_large:true,
    parent:"l4_yards",
    material_interest:["transit_windows", "substrate_supply"] },

  { id:"far_mooring", name:"Far Mooring", station:"achenar", band:"external",
    magnitude:1, electorate:7700,
    member:"Gustav Brightwater",
    held:{sc:1},
    at_large:true,
    parent:"achenar_point",
    material_interest:["transit_windows", "substrate_supply"] },

  { id:"sanctuary", name:"Sanctuary", station:"l5", band:"external",
    magnitude:1, electorate:6516,
    member:"Solveig Halstead",
    held:{rv:1},
    at_large:true,
    parent:"l5_refuge",
    material_interest:["transit_windows"] },

  /* THE CAPITAL TERRITORY. Non-voting: it returns a delegate who may speak
     and may not vote, so the seat is excluded from the district tier, from
     the chamber arithmetic and from every division. `nonVoting` is the flag
     the engine reads; see js/engine.js. */
  { id:"capital_territory", name:"Capital Territory", station:"winter_garden", band:"ring",
    magnitude:1, electorate:49200,
    member:"Rowan Charteris",
    held:{ind:1},
    at_large:true,
    nonVoting:true,
    parent:"winter_garden",
    material_interest:["charter_interpretation", "attestation_enforcement"],
    description:"The capital territory returns one delegate, chosen by the whole station and denied a vote on the floor. The electorate is the most transient in the Commonwealth: civil servants, the diplomatic corps, and the staff of the ministries, most of whom keep a vote in the district they came from. Turnout is high, and the result is read as a verdict on the government of the day rather than on the delegate.",
    tendency:"Non-voting by construction. The territory returns a delegate who may speak and may not vote. Its politics are the politics of the capital: whichever way the union leans, the Garden is where it is argued out, and the delegate is chosen to be nobody's." },
];
